<?php

session_start();
include "../connection.php";

require __DIR__ . '/../vendor/autoload.php';

use Razorpay\Api\Api;

if (isset($_SESSION["user_id"])) {
  $stmt = $connection->prepare("SELECT * FROM users WHERE user_id = ?");
  $stmt->bind_param("s", $_SESSION["user_id"]);
  $stmt->execute();

  $result = $stmt->get_result();
  $data = $result->fetch_assoc();

  $email = $data["email"];
  $contact_number = $data["contact_number"];

  $firstname = $data["firstname"];
  $lastname = $data["lastname"];
  $name = $firstname . " " . $lastname;

  $name_initials = $firstname[0] . $lastname[0];

  if (isset($_POST["proceedToPay"])) {
    $_SESSION["registration_data"] = $_POST;

    $event_id = $_POST["event_id"];

    $event_name = $_POST["event_name"];
    $event_start_date = $_POST["event_start_date"];
    $event_start_time = $_POST["event_start_time"];
    $event_venue = $_POST["event_venue"];
    $event_category = $_POST["event_category"];

    $event_type = $_POST["event_type"];

    $registration_fee = $_POST["registration_fee"];

    if ($event_type === "Solo") {
      $total_members = 1;
      $grand_total = $total_members * $registration_fee;
    } else {
      $student_email_array = $_POST["student_email"];
      $total_members = $_POST["team_members"];
      $grand_total = $total_members * $registration_fee;
    }

    $event_code = explode("-", $event_id)[1]; // SQLTREASURY
    $receipt = "EVT-" . $event_code . "-" . rand(1000, 9999);

    $keyId = "";
    $keySecret = "";

    $api = new Api($keyId, $keySecret);

    $orderData = [
      'receipt'         => $receipt,
      'amount'          => $grand_total * 100,
      'currency'        => 'INR',
      'payment_capture' => 1
    ];

    $order = $api->order->create($orderData);

    $order_id = $order['id']; // Generated by RazorPay

    $_SESSION["razorpay_order_id"] = $order_id;
  }
} else {
  header("location:../login.php");
  exit();
}

?>


<!doctype html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Confirm Payment - CEBS</title>

  <!-- Bootstrap -->
  <link
    href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
    rel="stylesheet" />
  <!-- Icons -->
  <link
    href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css"
    rel="stylesheet" />
  <!-- Google Fonts -->
  <link
    href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@600;700;800&family=DM+Sans:wght@300;400;500;600&display=swap"
    rel="stylesheet" />

  <link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/7.0.1/css/all.min.css"
    integrity="sha512-2SwdPD6INVrV/lHTZbO2nodKhrnDdJK9/kg2XD1r9uGqPo1cUbujc+IYdlYdEErWNu69gVcYgdxlmVmzTWnetw=="
    crossorigin="anonymous"
    referrerpolicy="no-referrer" />

  <link rel="stylesheet" href="../style.css" />
  <link rel="stylesheet" href="../auth.css" />

  <style>
    /* Payment Confirmation Page Styles */
    .payment-container {
      padding: 60px 20px;
      min-height: 100vh;
      position: relative;
    }

    .payment-card {
      max-width: 75vw;
      margin: 0 auto;
      background: rgba(255, 255, 255, 0.85);
      border: 1px solid rgba(14, 165, 233, 0.2);
      border-radius: 24px;
      backdrop-filter: blur(12px);
      box-shadow: 0 20px 50px rgba(14, 165, 233, 0.2);
      overflow: hidden;
      position: relative;
      z-index: 1;
    }

    .payment-header {
      background: linear-gradient(135deg,
          rgba(14, 165, 233, 0.1),
          rgba(56, 189, 248, 0.05));
      padding: 32px;
      border-bottom: 2px solid rgba(14, 165, 233, 0.15);
      text-align: center;
    }

    .payment-header h2 {
      font-family: "Playfair Display", serif;
      font-weight: 700;
      color: #1e293b;
      font-size: 1.8rem;
      margin-bottom: 8px;
    }

    .payment-header p {
      color: #64748b;
      font-size: 0.9rem;
      margin: 0;
    }

    .security-badge {
      display: inline-flex;
      align-items: center;
      gap: 6px;
      background: rgba(16, 185, 129, 0.1);
      color: #065f46;
      padding: 6px 14px;
      border-radius: 20px;
      font-size: 0.8rem;
      font-weight: 600;
      margin-top: 12px;
    }

    .security-badge i {
      color: #10b981;
    }

    .payment-body {
      padding: 32px;
    }

    .section-title {
      font-size: 0.85rem;
      font-weight: 700;
      color: #64748b;
      text-transform: uppercase;
      letter-spacing: 1px;
      margin-bottom: 16px;
      display: flex;
      align-items: center;
      gap: 8px;
    }

    .section-title i {
      color: #0ea5e9;
      font-size: 1rem;
    }

    .info-card {
      background: rgba(255, 255, 255, 0.6);
      border: 1px solid rgba(14, 165, 233, 0.15);
      border-radius: 14px;
      padding: 20px;
      margin-bottom: 24px;
    }

    .info-row {
      display: flex;
      justify-content: space-between;
      align-items: center;
      padding: 12px 0;
      border-bottom: 1px solid rgba(14, 165, 233, 0.1);
    }

    .info-row:last-child {
      border-bottom: none;
      padding-bottom: 0;
    }

    .info-row:first-child {
      padding-top: 0;
    }

    .info-label {
      color: #64748b;
      font-size: 0.85rem;
      font-weight: 500;
      display: flex;
      align-items: center;
      gap: 6px;
    }

    .info-label i {
      color: #0ea5e9;
      font-size: 0.85rem;
    }

    .info-value {
      color: #1e293b;
      font-weight: 600;
      font-size: 0.9rem;
      text-align: right;
    }

    .event-name {
      font-size: 1.1rem;
      color: #0ea5e9;
      font-weight: 700;
    }

    .participants-section {
      background: rgba(191, 219, 254, 0.2);
      border: 1px solid rgba(14, 165, 233, 0.2);
      border-radius: 14px;
      padding: 20px;
      margin-bottom: 24px;
    }

    .participant-item {
      display: flex;
      justify-content: space-between;
      align-items: center;
      padding: 12px 16px;
      background: rgba(255, 255, 255, 0.7);
      border-radius: 10px;
      margin-bottom: 10px;
      border: 1px solid rgba(14, 165, 233, 0.1);
    }

    .participant-item:last-child {
      margin-bottom: 0;
    }

    .participant-name {
      display: flex;
      align-items: center;
      gap: 10px;
      color: #1e293b;
      font-weight: 600;
      font-size: 0.9rem;
    }

    .participant-icon {
      width: 32px;
      height: 32px;
      background: linear-gradient(135deg, #0ea5e9, #0284c7);
      border-radius: 50%;
      display: flex;
      align-items: center;
      justify-content: center;
      color: #fff;
      font-size: 0.75rem;
      font-weight: 700;
    }

    .participant-amount {
      color: #1e293b;
      font-weight: 700;
      font-size: 0.95rem;
    }

    .team-badge {
      display: inline-flex;
      align-items: center;
      gap: 4px;
      background: linear-gradient(135deg,
          rgba(244, 63, 94, 0.15),
          rgba(251, 113, 133, 0.08));
      color: #be123c;
      padding: 4px 12px;
      border-radius: 20px;
      font-size: 0.75rem;
      font-weight: 600;
      border: 1px solid rgba(244, 63, 94, 0.25);
    }

    .pricing-breakdown {
      background: rgba(255, 255, 255, 0.6);
      border: 2px solid rgba(14, 165, 233, 0.2);
      border-radius: 14px;
      padding: 20px;
      margin-bottom: 24px;
    }

    .price-row {
      display: flex;
      justify-content: space-between;
      align-items: center;
      padding: 10px 0;
      font-size: 0.9rem;
    }

    .price-label {
      color: #64748b;
    }

    .price-value {
      color: #1e293b;
      font-weight: 600;
    }

    .price-divider {
      height: 1px;
      background: linear-gradient(90deg,
          transparent,
          rgba(14, 165, 233, 0.3),
          transparent);
      margin: 12px 0;
    }

    .total-row {
      display: flex;
      justify-content: space-between;
      align-items: center;
      padding: 16px 20px;
      background: linear-gradient(135deg,
          rgba(14, 165, 233, 0.1),
          rgba(56, 189, 248, 0.05));
      border-radius: 12px;
      margin-top: 12px;
    }

    .total-label {
      font-size: 1.1rem;
      font-weight: 700;
      color: #1e293b;
    }

    .total-amount {
      font-family: "Playfair Display", serif;
      font-size: 1.8rem;
      font-weight: 800;
      color: #0ea5e9;
    }

    .action-buttons {
      display: flex;
      gap: 12px;
      margin-top: 24px;
    }

    .btn-pay {
      flex: 1;
      background: linear-gradient(135deg, #10b981, #059669);
      color: #fff;
      border: none;
      border-radius: 12px;
      padding: 16px;
      font-family: "DM Sans", sans-serif;
      font-weight: 700;
      font-size: 1rem;
      cursor: pointer;
      box-shadow: 0 6px 24px rgba(16, 185, 129, 0.4);
      transition:
        transform 0.2s,
        box-shadow 0.2s;
      letter-spacing: 0.3px;
      display: flex;
      align-items: center;
      justify-content: center;
      gap: 8px;
    }

    .btn-pay:hover {
      transform: translateY(-2px);
      box-shadow: 0 8px 32px rgba(16, 185, 129, 0.5);
    }

    .btn-pay i {
      font-size: 1.1rem;
    }

    .btn-cancel {
      flex: 1;
      background: rgba(255, 255, 255, 0.8);
      color: #64748b;
      border: 2px solid rgba(14, 165, 233, 0.2);
      border-radius: 12px;
      padding: 16px;
      font-family: "DM Sans", sans-serif;
      font-weight: 600;
      font-size: 1rem;
      cursor: pointer;
      transition: all 0.2s;
      letter-spacing: 0.3px;
      display: flex;
      align-items: center;
      justify-content: center;
      gap: 8px;
    }

    .btn-cancel:hover {
      background: rgba(239, 68, 68, 0.1);
      border-color: rgba(239, 68, 68, 0.3);
      color: #dc2626;
    }

    .terms-notice {
      text-align: center;
      margin-top: 20px;
      padding: 16px;
      background: rgba(251, 146, 60, 0.08);
      border-radius: 10px;
      border: 1px solid rgba(251, 146, 60, 0.2);
    }

    .terms-notice p {
      margin: 0;
      font-size: 0.8rem;
      color: #64748b;
      line-height: 1.6;
    }

    .terms-notice a {
      color: #0ea5e9;
      text-decoration: none;
      font-weight: 600;
    }

    .terms-notice a:hover {
      color: #0284c7;
    }

    .payment-secure {
      display: flex;
      align-items: center;
      justify-content: center;
      gap: 12px;
      margin-top: 20px;
      padding: 12px;
      background: rgba(16, 185, 129, 0.1);
      border-radius: 10px;
      font-size: 0.8rem;
      color: #64748b;
      border: 1px solid rgba(16, 185, 129, 0.1);
    }

    .payment-secure img {
      height: 20px;
      opacity: 0.7;
    }

    .general-details {
      width: 30vw;
    }

    .payment-details {
      width: 30vw;
    }

    .payment-body {
      display: flex;
      flex-direction: row;
      justify-content: space-evenly;
    }

    .section-divider {
      width: 1px;
      background: rgba(14, 165, 233, 0.35);
      margin: 0 25px;
    }

    /* Mobile Responsive */
    @media (max-width: 768px) {
      .payment-container {
        padding: 40px 16px;
      }

      .payment-card {
        border-radius: 18px;
      }

      .payment-header {
        padding: 24px 20px;
      }

      .payment-header h2 {
        font-size: 1.5rem;
      }

      .payment-body {
        padding: 24px 20px;
      }

      .info-row {
        flex-direction: column;
        align-items: flex-start;
        gap: 6px;
      }

      .info-value {
        text-align: left;
      }

      .participant-item {
        padding: 10px 12px;
      }

      .participant-name {
        font-size: 0.85rem;
      }

      .participant-icon {
        width: 28px;
        height: 28px;
        font-size: 0.7rem;
      }

      .action-buttons {
        flex-direction: column;
      }

      .total-amount {
        font-size: 1.5rem;
      }
    }

    #loadingOverlay {
      position: fixed;
      top: 0;
      left: 0;
      width: 100%;
      height: 100%;
      background: rgba(0, 0, 0, 0.6);
      display: flex;
      align-items: center;
      justify-content: center;
      flex-direction: column;
      z-index: 9999;
      color: #fff;
      font-size: 18px;
      display: none;
    }

    .loader {
      border: 6px solid #f3f3f3;
      border-top: 6px solid #3498db;
      border-radius: 50%;
      width: 50px;
      height: 50px;
      animation: spin 1s linear infinite;
      margin-bottom: 10px;
    }

    @keyframes spin {
      0% {
        transform: rotate(0deg);
      }

      100% {
        transform: rotate(360deg);
      }
    }
  </style>
</head>

<body>
  <!-- 🔹 Top Bar -->
  <div class="top-bar py-2">
    <div
      class="container d-flex justify-content-between align-items-center flex-wrap gap-2">
      <span>
        <i class="bi bi-envelope me-1"></i>
        <a href="#">cebs.tech.team@gmail.com</a>
        <span class="mx-2 opacity-50">|</span>
        <i class="bi bi-telephone me-1"></i> +91 98765 43210
      </span>
      <span class="badge-accred">
        <i class="bi bi-patch-check me-1"></i> Approved by AICTE &nbsp;|&nbsp;
        NAAC Accredited
      </span>
    </div>
  </div>

  <!-- 🔹 Navbar -->
  <nav class="navbar navbar-expand-lg navbar-dark sticky-top">
    <div class="container">
      <a class="navbar-brand d-flex align-items-center gap-2" href="#">
        <div class="web-logo">
          <i class="fa-solid fa-building-columns fa-xl" id="logo-icon"></i>
        </div>
        R.N.G Patel Institute of Technology
      </a>

      <button
        class="navbar-toggler border-0"
        data-bs-toggle="collapse"
        data-bs-target="#navMenu"
        style="color: #fff">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navMenu">
        <ul class="navbar-nav ms-auto align-items-lg-center gap-lg-3">
          <li class="nav-item">
            <a class="nav-link" href="Dashboard.php">Dashboard</a>
          </li>
          <li class="nav-item dropdown-center dropdown">
            <a class="nav-link dropdown-toggle d-flex align-items-center" data-bs-toggle="dropdown" href="#events">Events</a>
            <ul class="dropdown-menu" style="border-radius: 14px; padding: 8px; min-width: 180px">
              <li><a class="dropdown-item d-flex align-items-center gap-3 py-2" href="AllEvents.php"> <i class="fa-solid fa-calendar-days"></i>
                  All Events</a></li>
              <li><a class="dropdown-item d-flex align-items-center gap-3 py-2" href="UpcomingEvents.php"><i class="fa-solid fa-clock"></i>
                  Upcoming Events</a></li>
              <li><a class="dropdown-item d-flex align-items-center gap-3 py-2" href="MyEvents.php"><i class="fa-solid fa-id-badge"></i>
                  My Events</a></li>
            </ul>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="MyTransactions.php">My Transactions</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="MyQRCodes.php">My QR Codes</a>
          </li>
          <li class="nav-item ms-lg-2  dropdown-center d-flex justify-content-center">
            <a
              class="profile-btn dropdown-toggle"
              role="button"
              data-bs-toggle="dropdown"
              href="#profile">
              <div class="profile-avatar"><?php echo $name_initials; ?></div>
              <span style="font-size: 0.85rem; font-weight: 500"><?php echo $name; ?></span>
            </a>

            <ul
              class="dropdown-menu shadow border-0"
              id="profile-dropdown-menu"
              style="border-radius: 14px; padding: 8px; min-width: 200px">
              <li>
                <a
                  class="dropdown-item d-flex align-items-center gap-3 py-2"
                  href="MyProfile.php"
                  id="edit-profile-opt">
                  <i class="fa-solid fa-user-pen"></i>
                  Edit Profile
                </a>
              </li>

              <li>
                <a
                  class="dropdown-item d-flex align-items-center gap-3 py-2 "
                  href="#"
                  id="logout-opt">
                  <i class="fa-solid fa-right-from-bracket"></i>
                  Logout
                </a>
              </li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <!-- Background orbs -->
  <div class="orb orb-1"></div>
  <div class="orb orb-2"></div>

  <div class="payment-container">
    <div class="payment-card">
      <!-- Header -->
      <div class="payment-header">
        <h2><i class="bi bi-shield-check me-2"></i>Confirm Payment</h2>
        <p>Review your booking details before proceeding to payment</p>
        <div class="security-badge">
          <i class="bi bi-lock-fill"></i>
          Secure Payment Gateway
        </div>
      </div>

      <!-- Body -->
      <div class="payment-body">
        <div class="general-details">
          <!-- Event Details Section -->
          <div class="section-title">
            <i class="bi bi-calendar-event"></i>
            Event Details
          </div>

          <div class="info-card">
            <div class="info-row">
              <div class="info-label">
                <i class="bi bi-bookmark-fill"></i>
                Event Name
              </div>
              <div class="info-value event-name"><?php echo $event_name; ?></div>
            </div>

            <div class="info-row">
              <div class="info-label">
                <i class="bi bi-calendar3"></i>
                Event Date
              </div>
              <div class="info-value"><?php echo date("jS F Y", strtotime($event_start_date)); ?></div>
            </div>

            <div class="info-row">
              <div class="info-label">
                <i class="bi bi-clock"></i>
                Time
              </div>
              <div class="info-value"><?php echo  date("h:i A", strtotime($event_start_time)); ?></div>
            </div>

            <div class="info-row">
              <div class="info-label">
                <i class="bi bi-geo-alt-fill"></i>
                Venue
              </div>
              <div class="info-value"><?php echo $event_venue; ?></div>
            </div>

            <div class="info-row">
              <div class="info-label">
                <i class="bi bi-tags-fill"></i>
                Category
              </div>
              <div class="info-value"><?php echo $event_category; ?></div>
            </div>
          </div>

          <!-- Participants Section - TEAM VERSION -->
          <?php if ($event_type === "Team"): ?>
            <div class="section-title">
              <i class="bi bi-people-fill"></i>
              Team Participants
              <span class="team-badge">
                <i class="bi bi-star-fill"></i>
                Team Entry
              </span>
            </div>

            <div class="participants-section">
              <div class="participant-item">
                <div class="participant-name">
                  <div class="participant-icon">1</div>
                  <span><?php echo $name; ?> (Team Leader)</span>
                </div>
                <div class="participant-amount">₹50</div>
              </div>

              <?php
              $stmt = $connection->prepare("SELECT firstname, lastname FROM users WHERE email = ?");
              for ($i = 1; $i < count($student_email_array); $i++) {
                $stmt->bind_param("s", $student_email_array[$i]);
                $stmt->execute();

                $result = $stmt->get_result();
                $data = $result->fetch_assoc();

                $fullname = $data["firstname"] . " " . $data["lastname"];

                echo "<div class='participant-item'>
                <div class='participant-name'>
                  <div class='participant-icon'>2</div>
                  <span>{$fullname}</span>
                </div>
                <div class='participant-amount'>₹{$registration_fee}</div>
              </div>";
              }
              ?>
            </div>
          <?php endif; ?>

          <!-- ALTERNATIVE: Solo Participant Version (Uncomment to use) -->
          <?php if ($event_type == "Solo"): ?>
            <div class="section-title">
              <i class="bi bi-person-fill"></i>
              Participant Details
            </div>

            <div class="participants-section">
              <div class="participant-item">
                <div class="participant-name">
                  <div class="participant-icon">
                    <i class="bi bi-person"></i>
                  </div>
                  <span><?php echo $name; ?></span>
                </div>
                <div class="participant-amount">₹<?php echo $registration_fee; ?></div>
              </div>
            </div>
          <?php endif; ?>

        </div>
        <div class="section-divider"></div>


        <div class="payment-details">
          <!-- Pricing Breakdown -->
          <div class="section-title">
            <i class="bi bi-receipt"></i>
            Payment Summary
          </div>

          <div class="pricing-breakdown">
            <div class="price-row">
              <div class="price-label">Entry Fee (<?php echo $total_members; ?> × ₹<?php echo $registration_fee; ?>)</div>
              <div class="price-value">₹<?php echo $grand_total; ?></div>
            </div>

            <div class="price-divider"></div>

            <div class="total-row">
              <div class="total-label">Grand Total</div>
              <div class="total-amount">₹<?php echo $grand_total; ?></div>
            </div>
          </div>

          <!-- Action Buttons -->
          <div class="action-buttons">
            <button class="btn-pay" id="paynow">
              <i class="bi bi-credit-card"></i>
              Pay Now
            </button>
            <button class="btn-cancel" onclick="cancelTransaction()">
              <i class="bi bi-x-circle"></i>
              Cancel
            </button>
          </div>

          <!-- Terms Notice -->
          <div class="terms-notice">
            <p>
              <i class="bi bi-info-circle me-1"></i>
              By proceeding, you agree to our
              <a href="#">Terms & Conditions</a> and
              <a href="#">Refund Policy</a>. All payments are processed
              securely through Razorpay.
            </p>
          </div>

          <!-- Payment Secure Badge -->
          <div class="payment-secure">
            <i
              class="bi bi-shield-check"
              style="color: #10b981; font-size: 1.2rem"></i>
            <div>
              <span>Secured by</span>
              <strong style="color: #0ea5e9">Razorpay</strong>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div id="loadingOverlay">
    <div class="loader"></div>
    <p>Processing your registration and generating your event pass...</p>
    <small>⚠️ Please do not refresh or close this page.</small>
  </div>

  <?php include "../footer.php"; ?>
  <script src="https://checkout.razorpay.com/v1/checkout.js"></script>
  <script>
    document.getElementById("paynow").onclick = function(e) {

      var options = {
        key: "rzp_test_SP4hV5BwGLglQX",
        amount: "<?php echo $grand_total * 100; ?>",
        order_id: "<?php echo $order_id; ?>",
        currency: "INR",

        name: "Event Registration",
        description: "<?php echo $event_category; ?> Registration Fee",

        prefill: {
          name: "<?php echo $name; ?>",
          email: "<?php echo $email; ?>",
          contact: "<?php echo $contact_number; ?>"
        },

        notes: {
          event_id: "<?php echo $event_id; ?>",
          event_category: "<?php echo $event_category; ?>"
        },

        modal: {
          escape: false,
          backdropclose: false
        },

        timeout: 300,

        handler: function(response) {

          document.getElementById('loadingOverlay').style.display = 'flex';

          var form = document.createElement("form");
          form.method = "POST";
          form.action = "BookEventData.php";

          var payment = document.createElement("input");
          payment.type = "hidden";
          payment.name = "razorpay_payment_id";
          payment.value = response.razorpay_payment_id;

          var order = document.createElement("input");
          order.type = "hidden";
          order.name = "razorpay_order_id";
          order.value = response.razorpay_order_id;

          var signature = document.createElement("input");
          signature.type = "hidden";
          signature.name = "razorpay_signature";
          signature.value = response.razorpay_signature;

          form.appendChild(payment);
          form.appendChild(order);
          form.appendChild(signature);

          document.body.appendChild(form);
          form.submit();
        },

        theme: {
          color: "#3399cc"
        }
      };

      var rzp = new Razorpay(options);
      rzp.on('payment.failed', function(response) {

        var form = document.createElement("form");
        form.method = "POST";
        form.action = "BookEventData.php";

        var payment = document.createElement("input");
        payment.type = "hidden";
        payment.name = "razorpay_payment_id";
        payment.value = response.error.metadata.payment_id;

        var order = document.createElement("input");
        order.type = "hidden";
        order.name = "razorpay_order_id";
        order.value = response.error.metadata.order_id;

        var code = document.createElement("input");
        code.type = "hidden";
        code.name = "error_code";
        code.value = response.error.code;

        var description = document.createElement("input");
        description.type = "hidden";
        description.name = "error_description";
        description.value = response.error.description;

        var reason = document.createElement("input");
        reason.type = "hidden";
        reason.name = "error_reason";
        reason.value = response.error.reason;

        var status = document.createElement("input");
        status.type = "hidden";
        status.name = "payment_status";
        status.value = "FAILED";

        form.appendChild(payment);
        form.appendChild(order);
        form.appendChild(code);
        form.appendChild(description);
        form.appendChild(reason);
        form.appendChild(status);

        document.body.appendChild(form);
        form.submit();

      });

      rzp.open();
    };

    // Cancel Transaction
    function cancelTransaction() {
      if (confirm("Are you sure you want to cancel this booking?")) {
        window.history.back();
      }
    }

    // Prevent accidental page close
  </script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
</body>

</html>